//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: AccountService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol AccounthandleLoginCall: ClientCallUnary {}

fileprivate final class AccounthandleLoginCallBase: ClientCallUnaryBase<LoginRequest, LoginResult>, AccounthandleLoginCall {
  override class var method: String { return "/Account/handleLogin" }
}

internal protocol AccounthandleRegisterCall: ClientCallUnary {}

fileprivate final class AccounthandleRegisterCallBase: ClientCallUnaryBase<RegistrationRequest, RegistrationResult>, AccounthandleRegisterCall {
  override class var method: String { return "/Account/handleRegister" }
}


/// Instantiate AccountServiceClient, then call methods of this protocol to make API calls.
internal protocol AccountService: ServiceClient {
  /// Synchronous. Unary.
  func handleLogin(_ request: LoginRequest, metadata customMetadata: Metadata) throws -> LoginResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleLogin(_ request: LoginRequest, metadata customMetadata: Metadata, completion: @escaping (LoginResult?, CallResult) -> Void) throws -> AccounthandleLoginCall

  /// Synchronous. Unary.
  func handleRegister(_ request: RegistrationRequest, metadata customMetadata: Metadata) throws -> RegistrationResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleRegister(_ request: RegistrationRequest, metadata customMetadata: Metadata, completion: @escaping (RegistrationResult?, CallResult) -> Void) throws -> AccounthandleRegisterCall

}

internal extension AccountService {
  /// Synchronous. Unary.
  func handleLogin(_ request: LoginRequest) throws -> LoginResult {
    return try self.handleLogin(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleLogin(_ request: LoginRequest, completion: @escaping (LoginResult?, CallResult) -> Void) throws -> AccounthandleLoginCall {
    return try self.handleLogin(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func handleRegister(_ request: RegistrationRequest) throws -> RegistrationResult {
    return try self.handleRegister(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleRegister(_ request: RegistrationRequest, completion: @escaping (RegistrationResult?, CallResult) -> Void) throws -> AccounthandleRegisterCall {
    return try self.handleRegister(request, metadata: self.metadata, completion: completion)
  }

}

internal final class AccountServiceClient: ServiceClientBase, AccountService {
  /// Synchronous. Unary.
  internal func handleLogin(_ request: LoginRequest, metadata customMetadata: Metadata) throws -> LoginResult {
    return try AccounthandleLoginCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleLogin(_ request: LoginRequest, metadata customMetadata: Metadata, completion: @escaping (LoginResult?, CallResult) -> Void) throws -> AccounthandleLoginCall {
    return try AccounthandleLoginCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func handleRegister(_ request: RegistrationRequest, metadata customMetadata: Metadata) throws -> RegistrationResult {
    return try AccounthandleRegisterCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleRegister(_ request: RegistrationRequest, metadata customMetadata: Metadata, completion: @escaping (RegistrationResult?, CallResult) -> Void) throws -> AccounthandleRegisterCall {
    return try AccounthandleRegisterCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol AccountProvider: ServiceProvider {
  func handleLogin(request: LoginRequest, session: AccounthandleLoginSession) throws -> LoginResult
  func handleRegister(request: RegistrationRequest, session: AccounthandleRegisterSession) throws -> RegistrationResult
}

extension AccountProvider {
  internal var serviceName: String { return "Account" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/Account/handleLogin":
      return try AccounthandleLoginSessionBase(
        handler: handler,
        providerBlock: { try self.handleLogin(request: $0, session: $1 as! AccounthandleLoginSessionBase) })
          .run()
    case "/Account/handleRegister":
      return try AccounthandleRegisterSessionBase(
        handler: handler,
        providerBlock: { try self.handleRegister(request: $0, session: $1 as! AccounthandleRegisterSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol AccounthandleLoginSession: ServerSessionUnary {}

fileprivate final class AccounthandleLoginSessionBase: ServerSessionUnaryBase<LoginRequest, LoginResult>, AccounthandleLoginSession {}

internal protocol AccounthandleRegisterSession: ServerSessionUnary {}

fileprivate final class AccounthandleRegisterSessionBase: ServerSessionUnaryBase<RegistrationRequest, RegistrationResult>, AccounthandleRegisterSession {}

